kind: Pod
apiVersion: v1
metadata:
  name: hostpath-provisioner
spec:
  containers:
    - name: hostpath-provisioner
      image: relaysh/relay-hostpath-provisioner:latest
      imagePullPolicy: "Always"
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOST_PATH
          value: /tmp/hostpath-provisioner
      volumeMounts:
        - name: pv-volume
          mountPath: /tmp/hostpath-provisioner
  serviceAccountName: hostpath-provisioner
  volumes:
    - name: pv-volume
      hostPath:
        path: /tmp/hostpath-provisioner
